#pragma once

// --- ID SETUP ---
#undef VENDOR_ID
#define VENDOR_ID 0xFEED
#undef PRODUCT_ID
#define PRODUCT_ID 0x6060
#undef MANUFACTURER
#define MANUFACTURER "DesignedbyGG"
#undef PRODUCT
#define PRODUCT "Ironclad v3"

#undef DEBOUNCE
#define DEBOUNCE 5

#define RGB_MATRIX_LED_PROCESS_LIMIT 20

#define OPENRGB_LED_COUNT 109
#undef DRIVER_LED_TOTAL
#define DRIVER_LED_TOTAL 109

// --- DISABLE RGB ANIMATIONS ---
#define DISABLE_RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define DISABLE_RGB_MATRIX_KEYPRESSES
#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_CHANGING
#define DISABLE_RGB_MATRIX_RAINDROPS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_CYCLE_ALL
#define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define DISABLE_RGB_MATRIX_DUAL_BEACON
#define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON


#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61

#define RAW_EPSIZE 64

// Save RAM by reducing Raw HID buffer capacity (required for 8KB RAM MCUs)
#define RAW_IN_CAPACITY 1
#define RAW_OUT_CAPACITY 1
