# --- CORE ---
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes

# --- OPENRGB ---
OPENRGB_ENABLE = yes
RAW_ENABLE = yes
RGB_MATRIX_ENABLE = yes

CONSOLE_ENABLE = no        
KEYBOARD_SHARED_EP = yes   
FIXED_CONTROL_ENDPOINT_SIZE = 32

# --- RAM SAVERS ---
EXTRAKEY_ENABLE = yes       # needed for volume/calc keys
VIA_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
GRAVE_ESC_ENABLE = no
WPM_ENABLE = no
SLEEP_LED_ENABLE = no
OS_DETECTION_ENABLE = no
RGBLIGHT_ENABLE = no
LOCKING_SUPPORT_ENABLE = no
DEBOUNCE_TYPE = sym_defer_g